---
- name: Deploy cloud-specific index pages and ensure nginx serves them
  hosts: webservers
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx if not present
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure nginx service is enabled and started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy cloud-specific index file
      ansible.builtin.copy:
        src: "index-{{ cloud }}.html"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      notify: Reload nginx

    - name: Wait for nginx to be ready
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 80
        timeout: 30

    - name: Verify page contents
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}"
        return_content: yes
        status_code: 200
      register: resp

    - name: Assert correct content is shown
      ansible.builtin.assert:
        that:
          - "'Welcome to AWS' in resp.content if cloud == 'aws' else 'Welcome to Azure' in resp.content"

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
